name: Backend CI (unit & E2E tests)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_call:
    secrets:
      password:
        description: 'needed for login'
        required: false

env:
  AUTH0_AUDIENCE:  ${{ secrets.AUTH0_AUDIENCE }}
  AUTH0_AUDIENCE2: ${{ vars.AUTH0_AUDIENCE }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Start docker containers
      env:
        AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      run: |
        docker-compose -f docker-compose-test.yml up --build --detach
        sleep 10  # wait for database to be ready

    - name: Run backend unit tests
      run: docker-compose exec -T backend npm run unit

    - shell: bash
      run: |
        echo "organization variable : ${{ secrets.AUTH0_AUDIENCE }}"
        echo "overridden variable : ${{ vars.AUTH0_AUDIENCE }}"
        echo "variable from shell environment : $AUTH0_AUDIENCE"
        echo "variable from shell environment : $AUTH0_AUDIENCE2"

    - name: Run backend E2E tests
      # with:
      #   AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      #   AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
      #   AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      #   AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      env:
        AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
        AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      run: docker-compose exec -T backend npm run e2e


    # - name: Run frontend E2E tests
    #   run: docker-compose exec -T frontend npm run e2e
