name: Backend CI (unit & integration tests)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_call:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Start docker containers
      run: |
        docker-compose -f docker-compose-test.yml up --build --detach
        sleep 10  # wait for database to be ready

    - name: Check .env
      run: |
        docker-compose exec -T backend ls -la
        docker-compose exec -T backend cp .env.txt .env
        docker-compose exec -T backend echo 'AUTH0_DOMAIN=${{ secrets.AUTH0_ISSUER_BASE_URL }}' >> .env
        docker-compose exec -T backend echo "AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}" >> .env
        docker-compose exec -T backend echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
        docker-compose exec -T backend echo "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> .env
        docker-compose exec -T backend cat .env

    - name: Run backend unit tests
      run: docker-compose exec -T backend npm run unit

    - name: Run backend Integration tests
      env:
        AUTH0_DOMAIN: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
        AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
        AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        DOMAIN: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
        AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
        ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
        CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      run: docker-compose exec -T backend npm run e2e

    # - name: Run frontend E2E tests
    #   run: docker-compose exec -T frontend npm run e2e
